version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: cd/backend.Dockerfile
    container_name: markdown-preview
    ports:
      - "3000:3000"
    volumes:
      - ../backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

